### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [30]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([86, 56, 54, 91, 31, 47, 25, 55, 20, 54, 75, 14, 68, 41, 48])

In [31]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[99, 90, 90, 36],
       [46, 65, 38, 51],
       [41, 91, 90, 42],
       [ 1, 46,  6, 98],
       [99, 12, 99, 49],
       [14, 82, 69, 62]])

In [ ]:
np.sort(a)[::-1] # slicing for rev

array([95, 84, 73, 72, 54, 39, 36, 33, 30, 29, 29, 24, 16,  5,  1])

In [ ]:
np.sort(b,axis = 0)

array([[18,  4, 18,  5],
       [19, 17, 28, 11],
       [38, 34, 31, 19],
       [48, 41, 36, 30],
       [72, 57, 73, 49],
       [73, 79, 95, 75]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code
np.append(a,200)

array([  1,  24,  16,  39,   5,  95,  73,  33,  30,  29,  54,  29,  72,
        84,  36, 200])

In [ ]:
b

array([[48, 79, 73, 19],
       [72, 34, 28, 49],
       [18, 17, 36,  5],
       [73, 57, 95, 75],
       [38,  4, 18, 30],
       [19, 41, 31, 11]])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis = 1) # give axis to append

array([[48., 79., 73., 19.,  1.],
       [72., 34., 28., 49.,  1.],
       [18., 17., 36.,  5.,  1.],
       [73., 57., 95., 75.,  1.],
       [38.,  4., 18., 30.,  1.],
       [19., 41., 31., 11.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [3]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [4]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
# code
a.shape

(15,)

In [8]:
np.expand_dims(a,axis = 0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis = 1)

array([[ 1],
       [24],
       [16],
       [39],
       [ 5],
       [95],
       [73],
       [33],
       [30],
       [29],
       [54],
       [29],
       [72],
       [84],
       [36]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [14]:
a

array([ 3, 92, 19, 50, 71, 89, 19, 81, 18, 21, 61, 70, 24, 20, 50])

In [17]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  4,  5,  7, 10, 11]),)

In [20]:
# replace all values > 50 with 0
np.where(a > 50, 0, a)

array([ 3,  0, 19, 50,  0,  0, 19,  0, 18, 21,  0,  0, 24, 20, 50])

In [109]:
np.where(a % 2 == 0, 0, a)

array([ 3,  0, 19,  0, 71, 89, 19, 81,  0, 21, 61,  0,  0,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [55]:
# code
a

array([ 3, 92, 19, 50, 71, 89, 19, 81, 18, 21, 61, 70, 24, 20, 50])

In [58]:
np.argmax(a)

np.int64(1)

In [49]:
b

array([[99, 90, 90, 36],
       [46, 65, 38, 51],
       [41, 91, 90, 42],
       [ 1, 46,  6, 98],
       [99, 12, 99, 49],
       [14, 82, 69, 62]])

In [59]:
np.argmax(b,axis = 0)

array([0, 2, 4, 3])

In [60]:
np.argmax(b,axis = 1)

array([0, 1, 1, 3, 0, 1])

In [52]:
# np.argmin
np.argmin(a)

np.int64(11)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [61]:
a

array([ 3, 92, 19, 50, 71, 89, 19, 81, 18, 21, 61, 70, 24, 20, 50])

In [63]:
np.cumsum(a)

array([  3,  95, 114, 164, 235, 324, 343, 424, 442, 463, 524, 594, 618,
       638, 688])

In [66]:
b

array([[99, 90, 90, 36],
       [46, 65, 38, 51],
       [41, 91, 90, 42],
       [ 1, 46,  6, 98],
       [99, 12, 99, 49],
       [14, 82, 69, 62]])

In [70]:
np.cumsum(b,axis=1)

array([[ 99, 189, 279, 315],
       [ 46, 111, 149, 200],
       [ 41, 132, 222, 264],
       [  1,  47,  53, 151],
       [ 99, 111, 210, 259],
       [ 14,  96, 165, 227]])

In [71]:
np.cumsum(b)

array([  99,  189,  279,  315,  361,  426,  464,  515,  556,  647,  737,
        779,  780,  826,  832,  930, 1029, 1041, 1140, 1189, 1203, 1285,
       1354, 1416])

In [72]:
# np.cumprod
np.cumprod(a)

array([                   3,                  276,                 5244,
                     262200,             18616200,           1656841800,
                31479994200,        2549879530200,       45897831543600,
            963854462415600,    58795122207351600,  4115658554514612000,
        6542084939802929920,  1714490280091737088, -6509206363960903680])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [76]:
a

array([ 3, 92, 19, 50, 71, 89, 19, 81, 18, 21, 61, 70, 24, 20, 50])

In [81]:
print(np.percentile(a,50))

50.0


In [82]:
print(np.median(a))

50.0


### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [83]:
# code
a

array([ 3, 92, 19, 50, 71, 89, 19, 81, 18, 21, 61, 70, 24, 20, 50])

In [85]:
np.histogram(a,bins = [0,50,100])

(array([7, 8]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [90]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [91]:
# code
a

array([ 3, 92, 19, 50, 71, 89, 19, 81, 18, 21, 61, 70, 24, 20, 50])

In [108]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([50, 70, 20, 50])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [126]:
# code
a

array([ 3, 92, 19, 50, 71, 89, 19, 81, 18, 21, 61, 70, 24, 20, 50])

In [127]:
np.flip(a)

array([50, 20, 24, 70, 61, 21, 18, 81, 19, 89, 71, 50, 19, 92,  3])

In [128]:
b

array([[99, 90, 90, 36],
       [46, 65, 38, 51],
       [41, 91, 90, 42],
       [ 1, 46,  6, 98],
       [99, 12, 99, 49],
       [14, 82, 69, 62]])

In [131]:
np.flip(b,axis = 1)

array([[36, 90, 90, 99],
       [51, 38, 65, 46],
       [42, 90, 91, 41],
       [98,  6, 46,  1],
       [49, 99, 12, 99],
       [62, 69, 82, 14]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [132]:
# code
a

array([ 3, 92, 19, 50, 71, 89, 19, 81, 18, 21, 61, 70, 24, 20, 50])

In [143]:
np.put(a,[0,1],[110,530])
a

array([110, 530,  19,  50,  71,  89,  19,  81,  18,  21,  61,  70,  24,
        20,  50])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [156]:
# code
a

array([110, 530,  19,  50,  71,  89,  19,  81,  18,  21,  61,  70,  24,
        20,  50])

In [157]:
np.delete(a,[0,2,4])

array([530,  50,  89,  19,  81,  18,  21,  61,  70,  24,  20,  50])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [162]:
# code
a

array([110, 530,  19,  50,  71,  89,  19,  81,  18,  21,  61,  70,  24,
        20,  50])

In [163]:
np.clip(a,a_min = 25, a_max = 75)

array([75, 75, 25, 50, 71, 75, 25, 75, 25, 25, 61, 70, 25, 25, 50])

In [172]:
# np.tile
arr = np.array([1,2,3])
np.tile(arr,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [175]:
# np.repeat
arr = np.array([1,2,3])
np.repeat(arr,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])