### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [ ]:
# Simple 1D Array
import numpy as np

a = np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [ ]:
# 2D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D
c = np.array([[ [1,2,3],[4,5,6] ],[ [7,8,9],[10,11,12] ]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# dtype
arr = np.array([1,2,3],dtype = float)
print(arr)

[1. 2. 3.]


In [ ]:
# np.arange
arr = np.arange(1,11,2) # same like range(start,stop,optional step)
print(arr)

[1 3 5 7 9]


In [ ]:
# with reshape
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# with reshape 4D
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
# np.ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# np.zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# random
np.random.random((3,4)) # range 0 --> 1

array([[0.22653891, 0.56423634, 0.07693215, 0.96701298],
       [0.25900078, 0.80427986, 0.1895647 , 0.25882309],
       [0.49105087, 0.4627655 , 0.43920495, 0.48819323]])

In [ ]:
# np.linspace
np.linspace(-10,10,10,dtype = int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# indentity (always a square matrix with ones on diagonal)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [ ]:
a1 = np.arange(10,dtype = np.int32) # Vector
a2 = np.arange(12,dtype = float).reshape(3,4) # Matrix
a3 = np.arange(8).reshape(2,2,2) # Tensor

In [ ]:
# ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [ ]:
# shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [ ]:
# size --> total no of items
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [ ]:
# itemsize ---> single item size
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [ ]:
# nbytes ---> total size
print(a1.nbytes)
print(a2.nbytes)
print(a3.nbytes)

72
96
64


### Changing dtype

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
# Scalar operations
# all arthmetic operators work (+,-,/,%,**)
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational operators (check every item) (all relational op works)
a2 >= 9

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [ ]:
# Vector operations
# all arthmetic operators work (+,-,/,%,**)
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
'''it rounds to the nearest possible number np.round(a1)
but if i first multiply a1 by 100 and then round it
it will give an array between the range of 1 to 100 instead of 0 to 1'''
a1

array([[64., 53., 89.],
       [26., 95., 33.],
       [27., 96., 54.]])

In [ ]:
# max/min/sum/prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1)) # sum of all
print(np.prod(a1)) # product of all

96.0
26.0
537.0
3444177302691840.0


In [ ]:
# by rows and col (0 for col and 1 for row)
print(np.max(a1,axis = 0)) # each col max
print(np.min(a1,axis = 1)) # each row min
print(np.sum(a1,axis = 1)) # each row sum
print(np.prod(a1,axis = 0 )) # each col prod

[64. 96. 89.]
[53. 26. 27.]
[206. 154. 177.]
[ 44928. 483360. 158598.]


In [ ]:
# mean/median/std/var (axis optional)
print(np.mean(a1, axis = 1))
print(np.median(a1, axis = 1))
print(np.std(a1))
print(np.var(a1))

[68.66666667 51.33333333 59.        ]
[64. 33. 54.]
26.741561493508772
715.1111111111111


In [ ]:
# trignometric functions
print(np.cos(a1)) # also tan or sin etc

[[ 0.39185723 -0.91828279  0.51017704]
 [ 0.64691932  0.73017356 -0.01327675]
 [-0.29213881 -0.18043045 -0.82930983]]


In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3) # Simple linear algebra matrix multiplication

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponent
print(np.log(a1))
print()
print(np.exp(a1))

[[4.15888308 3.97029191 4.48863637]
 [3.25809654 4.55387689 3.49650756]
 [3.29583687 4.56434819 3.98898405]]

[[6.23514908e+27 1.04137594e+23 4.48961282e+38]
 [1.95729609e+11 1.81123908e+41 2.14643580e+14]
 [5.32048241e+11 4.92345829e+41 2.83075330e+23]]


In [ ]:
# round/floor/ceil
print(np.round(np.random.random((3,3))*100)) # round to closest
print(np.floor(np.random.random((3,3))*100)) # round to floor (down)
print(np.ceil(np.random.random((3,3))*100)) # round to ceil (up)

[[90. 30. 29.]
 [83. 24. 34.]
 [19. 34. 27.]]
[[31. 10. 47.]
 [ 2. 33.  1.]
 [62.  0. 64.]]
[[ 9. 31. 13.]
 [66. 30.  8.]
 [69. 68. 58.]]


### Indexing & Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1,end = '\n\n')
print(a2,end = '\n\n')
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# Indexing 1D
print(a1[0])
print(a1[-2])

0
8


In [ ]:
# Indexing 2D [row,col]
print(a2[1,2])
print(a2[-2,-2])
print(a2[-1,-4])

6
6
8


In [ ]:
# Indexing 3D [array no,row,col]
print(a3[0,1,0])
print(a3[1,0,1])
print(a3[1,1,1])
print(a3[1,1,0])

2
5
7
6


In [ ]:
# Slicing 1D (Same as python lists)
print(a1)
print(a1[2:5])
print(a1[0::2])
print(a1[::-1])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [ ]:
# Slicing 2D
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
# Slicing 3D
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### Iterating

In [ ]:
# 1D
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
# 2D
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
# 3D
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
# for each item iteration
for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


### Reshaping

In [ ]:
# np.reshape (already done)
a_ = np.arange(10).reshape((2,5))
a_

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# np.transpose()
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel ---> convert ndim to 1D
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking (concatenation)

In [ ]:
a4 = np.arange(12).reshape((3,4))
a5 = np.arange(12,24).reshape((3,4))

In [ ]:
# horizontal stacking
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Spliting

In [ ]:
# operate as oposite of stack
# horizontal spliting
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
# vertical spliting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]