**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [17]:
#Code here
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [19]:
#Code here
a = int(input('enter first number: '))
b = int(input('enter 2nd number: '))
arr = np.random.random((a,b))

print('Array:\n',arr)
print('Avg:',np.mean(arr))

enter first number: 3
enter 2nd number: 4
Array:
 [[0.81938932 0.66592022 0.64444008 0.13764662]
 [0.84207442 0.95566653 0.03804434 0.27655285]
 [0.48347247 0.75201408 0.16408912 0.22725657]]
Avg: 0.5005472192830954


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [93]:
#Code here
def border_arr(a,b):
  arr = np.ones((a,b),dtype = int)
  arr[1:-1,1:-1] = 0
  return arr

border_arr(4,4)

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [37]:
#Code here ----> random.random() range from 0 to 1 both included
arr = np.linspace(0,1,12)[1:-1]
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [42]:
# No it must be a square matrix

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [101]:
#Code here
arr = np.zeros((5,5),dtype = int) + np.arange(5)
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [113]:
#code here
random_vector = np.random.randint(1,101,(10,2))
point = np.array([2,3])
distances = np.sqrt(np.sum((random_vector - point)**2, axis=1))
distances.astype(int)

array([ 90,  38, 102, 102, 100,  97,  85,  74,  56,  60])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [127]:
#Code here
print(np.arange(336).reshape((6,7,8))[1,5,3])
# [1,5,3]

99


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [166]:
#Code here
def rev_array(lst):
  lst = [int(i) for i in lst.split()]
  lst.reverse()
  return np.array(lst).astype(float)

l = '1 2 3 4 -8 -10'
print(rev_array(l))

[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [174]:
#Code here
input_array = np.array([1,2])
print('elements_count :',input_array.size)

elements_count : 2


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [214]:
#Code here
def softmax(arr):
  return np.exp(arr)/np.sum(np.exp(arr))

input_arr = input('Enter Numbers List: ')
input_arr = [float(i) for i in input_arr.split()]
output_arr = softmax(input_arr)
print(output_arr)

Enter Numbers List: 86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318
[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [206]:
#Coder here
def v_stacker(*args):
  for i in args:
    if type(i) != np.ndarray:
      raise ValueError('Only numpy arrays are allowed')
  return np.vstack(args)

a= np.array([[0,1,2,3,4],[5,6,7,8,9]])

b= np.array([[1,1,1,1,1],[1,1,1,1,1]])

c= np.array([[0.10117373,0.1677244,0.73764059,0.83166097,0.48985695],
[0.44581567,0.13502419,0.55692335,0.16479622,0.61193593]])

print(v_stacker(a,b,c))

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [266]:
#Code here
def date_array(start ,end ):
  if type(start) == str and type(end) == str:
    start_num = int(start.split('-')[2])
    end_num = int(end.split('-')[2])
    date = start.split('-')
    new_list = [f'{date[0]}-{date[1]}-{i}' for i in range(start_num,end_num+1)]
    return np.array(new_list)

  else:
    raise ValueError('Please write inputs in String only')

print(date_array(start = '2020-09-15', end = '2020-09-25'))

['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']


###`Q-14:` Subtract the mean of each row from a matrix.

In [366]:
#code here
arr = np.arange(12,24).reshape(3,4)
row_means = np.mean(arr,axis = 1, keepdims = True)
arr - row_means

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [314]:
#Code here
arr = np.arange(12,24).reshape(3,4)
arr

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [315]:
temp = arr[:,0].copy()
arr[:,0] = arr[:,1]
arr[:,1] = temp
arr

array([[13, 12, 14, 15],
       [17, 16, 18, 19],
       [21, 20, 22, 23]])

###`Q-16:` Replace odd elements in arrays with -1.

In [316]:
#Code here
arr = np.arange(12,24).reshape(3,4)
arr

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [321]:
arr[~(arr % 2 == 0)] = -1
arr

array([[12, -1, 14, -1],
       [16, -1, 18, -1],
       [20, -1, 22, -1]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [332]:
#Code here
a = np.array([6,3,1,5,8])
b = np.array([3,2,1,7,2])

In [335]:
max_arr = np.vstack((a,b)).max(axis = 0)
print(max_arr)

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [392]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[1232, 9603, 6648, 6707, 7530],
       [4026, 1391, 7418, 3019, 4750],
       [8544, 9810, 1864, 2680,  261],
       [9968, 7791, 4435, 3962, 6812],
       [7849, 8689, 4988, 3355,  235],
       [6815, 8726,  885, 3374, 2042],
       [9229, 7144, 6390, 5620, 7984],
       [5873, 2463, 3882, 1721, 3356]])

In [401]:
# Fetch Every alternate column of the array
x = arr1[:,::2]
x

array([[1232, 6648, 7530],
       [4026, 7418, 4750],
       [8544, 1864,  261],
       [9968, 4435, 6812],
       [7849, 4988,  235],
       [6815,  885, 2042],
       [9229, 6390, 7984],
       [5873, 3882, 3356]])

In [403]:
# Normalise the given array
xNorm = (x - np.min(x)) / (np.max(x) - np.min(x))
print(xNorm)

[[0.10243501 0.65889243 0.74951197]
 [0.38949964 0.73800473 0.46388575]
 [0.85369362 0.16736875 0.00267132]
 [1.         0.43152163 0.67574232]
 [0.78228706 0.48833864 0.        ]
 [0.67605055 0.06678311 0.18565704]
 [0.92407274 0.63238467 0.7961574 ]
 [0.57926641 0.37470461 0.32066167]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [364]:
#Code here
def max_number(arr,n):
  if n <= arr.size and arr.ndim == 1:
    index = arr.size - n
    return np.sort(arr)[index]

arr = np.array([12,34,40,7,1,0])
n = 3

print(max_number(arr,n))

12


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [377]:
#code here
a = np.array([1,2,3])
a

array([1, 2, 3])

In [391]:
np.hstack((np.repeat(a,a.size),np.tile(a,a.size)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])